defaults: &defaults
  HOLLIS_RECORD_XPATH: "//*[local-name()='relatedItem'][@otherType='HOLLIS record']/*[local-name()='location']/*[local-name()='url']"
  FINDING_AID_XPATH: "//*[local-name()='relatedItem'][@otherType='Finding Aid']/*[local-name()='location']/*[local-name()='url']"
  CREATOR_XPATH: ".//*[local-name()='name']"
  REPOSITORY_XPATH: ".//*[local-name()='location']/*[local-name()='physicalLocation'][@type='repository']"
  COLLECTION_TITLE_XPATH: "//*[local-name()='relatedItem'][@displayLabel='collection']/*[local-name()='titleInfo']/*[local-name()='title']"
  COLLECTION_TITLE_DATE_XPATH: "//*[local-name()='relatedItem'][@displayLabel='collection']/*[local-name()='originInfo']/*[local-name()='dateCreated']"

development:
  <<: *defaults
  ALEPH_URL: http://id.lib.harvard.edu/aleph/
  
  
test:
  <<: *defaults
  ALEPH_URL: http://id.lib.harvard.edu/aleph/

production:
  <<: *defaults
  ALEPH_URL: http://id.lib.harvard.edu/aleph/
  