#Structure:
#
#  - spotlight-field: xxx (field names should be separated with dashes except for the suffix: firstpart-secondpart_ssim or _tesim)
#    multivalue-facets: "yes" (optional) - use this for splitting out multiple values to be faceted individually (ex - subjects)
#    default-value: xxx (optional)
#    delimiter: xxx (optional, what to separate all path values with.  Defaults to a space)
#    mods:
#        - path: xxx (repeatable - all path fields will be concatenated)
#          delimiter: " "
#          attribute: displayLabel
#          attribute-value: collection
#          mods-path: xxx 
#          mods-value: xx
#          subpaths: 
#            - subpath: xxx
#            - subpath: xxx
#    xpath: 
#        - xpath_value: xxx
#          xpath_namespace_prefix: xxx (optional, default is mods)
#          xpath_namespace_def: xxx (optional, default is mods)
#
# Hard coded Spotlight fields:
# full_image_url_ssm, spotlight_upload_description_tesim, thumbnail_url_ssm
#
- spotlight-field: unique-id_tesim
  mods:
      - path: recordInfo/recordIdentifier
- spotlight-field: full_title_tesim
  delimiter: ": "
  mods:
      - path: titleInfo
        delimiter: " "
        subpaths:
          - subpath: nonSort
          - subpath: title
      - path: titleInfo/subTitle
- spotlight-field: citation-title_tesim
  mods:
      - path: titleInfo/title
#plain_name is a custom name used in the mods gem
- spotlight-field: creator_tesim
  mods:
      - path: plain_name
        delimiter: " , "
        mods-path: role/roleTerm
        mods-value: creator
        subpaths:
          - subpath: namePart
- spotlight-field: start-date_tesim
  mods:
      - path: originInfo/dateCreated
        delimiter: "|"
        attribute: point
        attribute-value: start
- spotlight-field: end-date_tesim
  mods:
      - path: originInfo/dateCreated
        delimiter: "|"
        attribute: point
        attribute-value: end
- spotlight-field: publisher_tesim
  mods:
      - path: originInfo/publisher
- spotlight-field: date_tesim
  mods:
      - path: originInfo/dateCreated
        attribute: '!point'
        attribute-value: 
- spotlight-field: classification_ssim
  mods:
      - path: classification
- spotlight-field: classification_tesim
  mods:
      - path: classification
- spotlight-field: contributer_tesim
  delimiter: "|"
  mods:
      - path: plain_name
        delimiter: " , "
        mods-path: role/roleTerm
        mods-value: '!creator'
        subpaths:
          - subpath: namePart
- spotlight-field: spotlight_upload_description_tesim
  delimiter: "|"
  mods: 
      - path: abstract
- spotlight-field: format_tesim
  delimiter: "|"
  mods:
      - path: physicalDescription/extent
- spotlight-field: physical-description_tesim
  delimiter: "|"
  mods:
      - path: physicalDescription/note
- spotlight-field: language_ssim
  default-value: English
  delimiter: "|"
  mods: 
      - path: language/languageTerm
- spotlight-field: language_tesim
  default-value: English
  delimiter: "|"
  mods: 
      - path: language/languageTerm
- spotlight-field: repository_ssim
  delimiter: "|"
  mods:
      - path: location/physicalLocation
        attribute: type
        attribute-value: repository
- spotlight-field: repository_tesim
  delimiter: "|"
  mods:
      - path: location/physicalLocation
        attribute: type
        attribute-value: repository
- spotlight-field: subjects_ssim
  multivalue-facets: "yes"
  delimiter: "|"
  mods:
      - path: subject
        delimiter: "--"
        subpaths:
          - subpath: name/namePart
          - subpath: topic
          - subpath: geographic
          - subpath: genre
- spotlight-field: subjects_tesim
  delimiter: "|"
  mods:
      - path: subject
        delimiter: "--"
        subpaths:
          - subpath: name/namePart
          - subpath: topic
          - subpath: geographic
          - subpath: genre
- spotlight-field: type_ssim
  delimiter: "|"
  mods:
      - path: genre
- spotlight-field: type_tesim
  delimiter: "|"
  mods:
      - path: genre
- spotlight-field: origin_ssim
  mods:
      - path: originInfo/place/placeTerm
- spotlight-field: origin_tesim
  mods:
      - path: originInfo/place/placeTerm
- spotlight-field: note_tesim
  delimiter: "|"
  mods:
      - path: note
- spotlight-field: thumbnail_url_ssm
  mods:
      - path: location/url
        attribute: access
        attribute-value: preview
- spotlight-field: full_image_url_ssm
  mods:
      - path: location/url
        attribute: access
        attribute-value: raw object
- spotlight-field: rights_tesim
  mods:
      - path: accessCondition
- spotlight-field: creation-date_ssim
  mods:
      - path: originInfo/dateIssued
      - path: originInfo/dateCreated
        attribute: '!point'
        attribute-value: 
- spotlight-field: creation-date_tesim
  mods:
      - path: originInfo/dateIssued
      - path: originInfo/dateCreated
        attribute: point
        attribute-value: start
- spotlight-field: edition_tesim
  mods:
      - path: originInfo/edition
- spotlight-field: identifier_tesim
  delimiter: "|"
  mods:
      - path: identifier
- spotlight-field: contents_tesim
  delimiter: "|"
  mods:
      - path: tableOfContents
- spotlight-field: contents_ssim
  delimiter: "|"
  mods:
      - path: tableOfContents
- spotlight-field: xpath-test_ssim
  multivalue-facets: "yes"
  xpath: 
      - xpath-value: "//mods:location/mods:physicalLocation[@type='repository']"
      - xpath-value: "//mods:relatedItem[@type='host']/mods:location/mods:physicalLocation[@type='repository']"
- spotlight-field: xpath-test-harvard-namespace_ssim
  multivalue-facets: "yes"
  xpath: 
      - xpath-value: "//HarvardDRS:DRSMetadata/HarvardDRS:metsLabel"
        xpath-namespace-prefix: "HarvardDRS"
        xpath-namespace-def: "http://hul.harvard.edu/ois/xml/ns/HarvardDRS"
      - xpath-value: "//HarvardDRS:DRSMetadata/HarvardDRS:ownerCodeDisplayName"
        xpath-namespace-prefix: "HarvardDRS"
        xpath-namespace-def: "http://hul.harvard.edu/ois/xml/ns/HarvardDRS"
- spotlight-field: xpath-mods-test_ssim
  mods:
      - path: location/physicalLocation
        attribute: type
        attribute-value: repository
  xpath:
      - xpath-value: "//mods:relatedItem[@type='host']/mods:location/mods:physicalLocation[@type='repository']"
         